[versions]
agp = "9.3.2"
coil = "3.6.0"
kotlin = "2.4.10"
material = "1.14.0"
viewpager = "1.1.0"

[libraries]
androidx-viewpager = { module = "androidx.viewpager:viewpager", version.ref = "viewpager" }
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

